name: Reusable • Build & Deploy MkDocs to Pages

on:
  workflow_call:
    inputs:
      python_version: { type: string, default: "3.12" }
      publish_dir:    { type: string, default: "site" }
      aggregate_docs: { type: string, default: "" }
    secrets:
      GH_TOKEN:
        required: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ inputs.python_version }} }
      - uses: astral-sh/setup-uv@v3
      - run: uv sync
      # (optional aggregation step here…)
      - run: uv run mkdocs build --strict
      - uses: actions/upload-pages-artifact@v3
        with: { path: ${{ inputs.publish_dir }} }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
